name: Place Tux CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Copy raw files
        run: |
          mkdir .build

      - name: Update hash
        run: echo $(git rev-parse "$GITHUB_SHA") > ./.build/bot_hash

      - uses: EndBug/add-and-commit@v9
        with:
          add: "./.build"
          committer_name: GitHub Actions
          committer_email: actions@github.com

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build/
          keep_files: true
          full_commit_message: deploy image
